### ISSUE TITLE
Department folders with many children cause errors

### ISSUE THREAD

**Issue by phette23** [cca/panopto_course_group_copy#4]
Department folders with many (>50?) children throw an error when we try to get the identifiers for all their children with `SessionManagement.service.GetFoldersById`. This happened with _at least_ FINAR and Metacourses for 2021FA but probably some other large departments, too.

The problem is in `dept_folder`. We need to batch the list of child folders GUIDs into fixed-length chunks, this should be easy to do with `itertools`.

The error looks like this:

<details>

```py
Traceback (most recent call last):
  File "/Users/ephetteplace/Code/aPanopto/group-copy/app.py", line 241, in <module>
    main(args)
  File "/Users/ephetteplace/Code/aPanopto/group-copy/app.py", line 182, in main
    globals()[f"{args.folder_type}_folder"](args.folder_id)
  File "/Users/ephetteplace/Code/aPanopto/group-copy/app.py", line 158, in dept_folder
    child_folders = SessionManagement.service.GetFoldersById(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ephetteplace/.local/share/virtualenvs/group-copy-jS6fgwXJ/lib/python3.11/site-packages/zeep/proxy.py", line 46, in __call__
    return self._proxy._binding.send(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ephetteplace/.local/share/virtualenvs/group-copy-jS6fgwXJ/lib/python3.11/site-packages/zeep/wsdl/bindings/soap.py", line 135, in send
    return self.process_reply(client, operation_obj, response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ephetteplace/.local/share/virtualenvs/group-copy-jS6fgwXJ/lib/python3.11/site-packages/zeep/wsdl/bindings/soap.py", line 229, in process_reply
    return self.process_error(doc, operation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ephetteplace/.local/share/virtualenvs/group-copy-jS6fgwXJ/lib/python3.11/site-packages/zeep/wsdl/bindings/soap.py", line 317, in process_error
    raise Fault(
zeep.exceptions.Fault: Unknown fault occured
```

</details>

**Comment by phette23** [comment]
Batching the calls to `GetFoldersById` didn't solve the problem. There's something corrupted about a child folder under FINAR or Metacourses it appears. Those two departments do have the greatest number of child folders though, that must be related.

**Comment by phette23** [comment]
If we request child folders one at a time the bug does not occur. I wasn't able to pinpoint it either with a script like this:

```py
folder_id = "52dc1e83-5ee7-4ec1-b86d-ad6a01087d69"
# this works
folder = SessionManagement.service.GetFoldersById(
    auth=AuthenticationInfo, folderIds=[folder_id]
)[0]
for i in range(1, 50):
    child_guids = folder["ChildFolders"]["guid"][0:i]
    try:
        child_folders = SessionManagement.service.GetFoldersById(
            auth=AuthenticationInfo, folderIds={"guid": child_guids}
        )
        print(f"Got {len(child_folders)} child folders")
    except:
        print(f"Failed to get {i} child folders")
```

that never hit an error.
